name = "bitcoinperception-redirect"
main = "src/index.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "bitcoinperception.com/*", zone_name = "bitcoinperception.com" },
  { pattern = "www.bitcoinperception.com/*", zone_name = "bitcoinperception.com" }
]
